### ISSUE TITLE
Feature request: Dropbox upload

### ISSUE THREAD

**Issue by Nik0lashka** [Exolius/SimpleBackup#29]
It would be great to add possibility to upload backups to the dropbox, for example like [here](https://github.com/ltguide/CraftBukkit-MineBackup).

**Comment by RoboMWM** [comment]
I don't think this plugin does any sort of remote backups. Not to mention if this is PR'd (the original author is no longer actively developing bukkit plugins), requests for other online services (such as OneDrive) will appear, and ultimately make this a little less "simple."

In other words, I don't think it fits this plugin's laser-focus purpose.

**Comment by Nik0lashka** [comment]
If somebody would like to upload backups to their dropbox one can use [this](https://github.com/andreafabrizi/Dropbox-Uploader).
